version: "3.9"

services:
  backend:
    build: waitlist-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: waitlist-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  db:
    build: waitlist-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: