# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19QaLfawBSDdjQorEBiONRubjmtZPlQQO
"""

import pydot

def create_graph(nodes, edges):
    graph = pydot.Dot(graph_type="digraph")

    for node_name, node_label in nodes.items():
        node = pydot.Node(node_name, shape="record", label=node_label)
        graph.add_node(node)

    for source, target, label in edges:
        graph.add_edge(pydot.Edge(source, target, label=label))

    return graph

# Database schema
database_nodes = {
    "Queues": "{Queues|* queue_id : int\\l- course_id : int\\l- user_id : int\\l+ queue_estimated_time : int\\l+ queue_request_status : enum('DONE', 'IN_PROGRESS', 'WAITING, 'CANCELED')\\l+ queue_topic_description : varchar(255)\\l+ queue_timestamp : timestamp\\l- queue_instructor_user_id : int\\l}",
    "Courses": "{Courses|* course_id : int\\l+ course_name : varchar(255)\\l+ course_description : varchar(255)\\l+ course_student_join_code : varchar(255)\\l+ course_instructor_join_code : varchar(255)\\l}",
    "Users": "{Users|* user_id : int\\l+ user_name : varchar(255)\\l+ user_email : varchar(255)\\l+ user_password : varchar(255)\\l}",
    "Permissions": "{Permissions|* permission_id : int\\l- course_id : int\\l- user_id : int\\l+ permission_type : enum('instructor', 'student')\\l+ permission_location : varchar(255)\\l}"
}

database_edges = [
    ("Courses", "Queues", "course_id"),
    ("Users", "Queues", "user_id"),
    ("Users", "Queues", "queue_instructor_id"),
    ("Courses", "Permissions", "course_id"),
    ("Users", "Permissions", "user_id")
]

database_graph = create_graph(database_nodes, database_edges)

# UI schema
ui_nodes = {
    "Index": "{Index|* Register\\l* Login\\l* Learn About Website\\l}",
    "Register": "{Register|* Register With Wisc ID\\l}",
    "Login": "{Login|* Login With Wisc ID\\l}",
    "Dashboard": "{Dashboard|* Access Your Courses\\l* Join New Course (as Instructor or Student)\\l* Create New Course (as Instructor)\\l}",
    "InstructorView": "{InstructorView|* See Live Course Queue\\l* Help Next Student\\l* Kick Out No Show Student\\l* Edit Info Seen By Students\\l}",
    "StudentView": "{StudentView|* See Live Course Queue\\l* Edit Question and Estimated Time\\l* Enter/Leave Queue\\l* See Instructor Info When Selected\\l}"
}

ui_edges = [
    ("Index", "Login", "Account Already Exists"),
    ("Index", "Register", "Account Needed"),
    ("Register", "Login", "Account Created"),
    ("Login", "Dashboard", "Sign In Successful"),
    ("Dashboard", "InstructorView", "Instructor Permissions for Course"),
    ("Dashboard", "StudentView", "Student Permissions for Course")
]

ui_graph = create_graph(ui_nodes, ui_edges)

# Save graphs as PNG images
database_graph.write_png("database_schema.png")
ui_graph.write_png("ui_schema.png")